[package]
name = "slack_http_types"
authors.workspace = true
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
time = { workspace = true }
